services:
  - type: web
    name: bonsai-chess-api
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bonsai-chess-db
          property: connectionString
      - key: PORT
        value: 8080

    healthCheckPath: /

databases:
  - name: bonsai-chess-db
    plan: free
